# Generated by Django 4.0.4 on 2022-05-17 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_camerasbaleares_camerascat_camerascoruña_and_more'),
    ]

    operations = [
 
        migrations.RemoveField(
            model_name='camerasbaleares',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='camerasbaleares',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='camerasbaleares',
            name='location',
        ),
    ]
