# Generated by Django 4.0.4 on 2022-05-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_tarfficcamera_trafficcamera_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='TrafficCamera',
            new_name='traffic_cameras',
        ),
    ]
