# Generated by Django 4.0.4 on 2022-05-17 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_post_remove_camerasbaleares_date_published_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
