# Generated by Django 4.0.4 on 2022-05-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_trafficcamera_location_traffic_cameras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='trafficcamera',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
