# Generated by Django 4.0.4 on 2022-05-11 11:50

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_location_name_alter_trafficcamera_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficcamera',
            name='name',
        ),
        migrations.AddField(
            model_name='trafficcamera',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='trafficcamera',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trafficcamera',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
        migrations.AddField(
            model_name='trafficcamera',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trafficcamera',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='trafficcamera',
            name='title',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trafficcamera',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
