# Generated by Django 4.0.4 on 2022-05-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_trafficcamera_name_trafficcamera_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficcamera',
            name='lat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trafficcamera',
            name='lon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
