# Generated by Django 4.0.4 on 2022-05-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_trafficcamera_lat_trafficcamera_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficcamera',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
