# Generated by Django 4.0.4 on 2022-05-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_trafficcamera_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficcamera',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trafficcamera',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
