# Generated by Django 4.0.4 on 2022-05-13 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_camerascam_delete_location_delete_trafficcamera'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CamerasCAM',
            new_name='CamerasComMadrid',
        ),
    ]
